default_language_version:
  node: 16.15.0
  ruby: 2.7.2

repos:
  # yaml formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier

  # Ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.2"
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
